import { Button, VerticalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 300px;
    height: 300px;
    title: "Solana Price";
    in-out property <string> price: "0";
    callback request-increase-value();
    VerticalBox {
        spacing: 1px;
        VerticalLayout {
            alignment: center;
            HorizontalLayout {
                spacing: 10px;
                Image {
                    source: @image-url("icon/Solana.png");
                    width: 25px;
                }

                Text {
                    font-size: 24px;
                    text: "SOL";
                    vertical-alignment: center;
                }
            }

            Text {
            font-size: 24px;
            horizontal-alignment: right;
            text: "SOL Price: $\{root.price}";
        }
    }
        

        Button {
            height: 50px;
            primary: true;
            text: "Refresh";
            clicked => {
                root.request-increase-value();
            }
        }
    }
}
